server:
  port: '8080'
  error:
    include-stacktrace: ON_PARAM
    include-exception: 'false'
    include-binding-errors: always
    include-message: always

management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  devtools:
    restart:
      quiet-period: 1s
      poll-interval: 2s
  data:
    mongodb:
      port: '27017'
      host: localhost
      database: client_db
      uri: mongodb://hh:herve@localhost:27017
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: 'true'
    properties:
      hibernate:
        default_schema: client_db

